// Angular
import { Injectable } from '@angular/core';

// Firebase
import { AngularFireDatabase } from 'angularfire2/database';
import { AngularFireAuth } from 'angularfire2/auth';
import * as firebase from 'firebase/app';

// RxJs
import { Observable } from 'rxjs/Observable';

// App
import { ArticleModel } from '../models/article.model';

@Injectable()
export class ArticleService {
    private userId: string = null;
    public list: Observable<ArticleModel[]> = null;

    public constructor(
        private db: AngularFireDatabase,
        private auth: AngularFireAuth,
    ) {
        this.auth.authState.subscribe(
            (user: firebase.User) => {
                if (user) {
                    this.userId = user.uid;

                    this.list = this.db.list(`articles/${this.userId}`).snapshotChanges()
                        .map(actions => {
                            return actions.map(item => {
                                return {
                                    id: item.payload.key,
                                    title: item.payload.val().title,
                                    description: item.payload.val().description,
                                    text: item.payload.val().text,
                                };
                            });
                        });
                }
            });
    }

    public push(item: ArticleModel): void {
        if (this.userId) {
            // Generate a reference to a new location and add some data using push()
            const ref = this.db.list(`articles/${this.userId}`).push({});

            this.db.object(`articles/${this.userId}/${ref.key}`).set(new ArticleModel({
                id: ref.key,    // Get the unique key generated by push()
                projectId: item.projectId,
                title: item.title,
                description: item.description,
                text: item.text,
            }));
        }
    }

    public update(item: ArticleModel): void {
        if (this.userId) {
            this.db.object(`articles/${this.userId}/${item.id}`).set(new ArticleModel(item));
        }
    }

    public remove(item: ArticleModel): void {
        if (this.userId) {
            this.db.list(`articles/${this.userId}`).remove(item.id);
        }
    }
}
