// Angular
import { Injectable } from '@angular/core';

// Firebase
import { AngularFireDatabase } from 'angularfire2/database';
import { AngularFireAuth } from 'angularfire2/auth';
import * as firebase from 'firebase/app';

// RxJs
import { Observable } from 'rxjs/Observable';

// App
import { ProjectModel } from '../models/project.model';

@Injectable()
export class ProjectService {
    private _item = 'projects';

    private userId: string = null;
    public list: Observable<ProjectModel[]> = null;

    public constructor(
        private db: AngularFireDatabase,
        private auth: AngularFireAuth,
    ) {
        this.auth.authState.subscribe(
            (user: firebase.User) => {
                if (user) {
                    this.userId = user.uid;

                    this.list = this.db.list(`${this._item}/${this.userId}`).snapshotChanges()
                        .map(actions => actions.map(item => new ProjectModel(item.payload.val())));
                }
            });
    }

    public push(item: ProjectModel): void {
        if (this.userId) {
            // Generate a reference to a new location and add some data using push()
            const ref = this.db.list(`${this._item}/${this.userId}`).push({});

            // Get the unique key generated by push()
            item.id = ref.key;
            this.db.object(`${this._item}/${this.userId}/${ref.key}`).set(new ProjectModel(item));
        }
    }

    public update(item: ProjectModel): void {
        if (this.userId) {
            this.db.object(`${this._item}/${this.userId}/${item.id}`).set(new ProjectModel(item));
        }
    }

    public remove(item: ProjectModel): void {
        if (this.userId) {
            this.db.list(`${this._item}/${this.userId}`).remove(item.id);
        }
    }
}
